services:

  postgres:
    image: postgres:16-alpine

    container_name: postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - fintech-network



  zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}

    container_name: zookeeper

    restart: unless-stopped

    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}

    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${ZOOKEEPER_CLIENT_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - fintech-network



  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}

    container_name: kafka

    restart: unless-stopped

    depends_on:
      zookeeper:
        condition: service_healthy

    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"

    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:${KAFKA_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - fintech-network



  auth-service:
    build:
      context: ./auth-services
      dockerfile: Dockerfile

    container_name: auth-service

    restart: unless-stopped

    env_file:
      - .env

    environment:
      SERVER_PORT: ${AUTH_SERVICE_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      JAVA_OPTS: ${JAVA_OPTS}
      SPRING_DATASOURCE_URL: ${AUTH_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${POSTGRES_DRIVER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}
      SPRING_JPA_OPEN_IN_VIEW: ${SPRING_JPA_OPEN_IN_VIEW}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"

    depends_on:
      postgres:
        condition: service_healthy

      kafka:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AUTH_SERVICE_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - fintech-network



  user-service:
    build:
      context: ./user-services
      dockerfile: Dockerfile

    container_name: user-service

    restart: unless-stopped

    env_file:
      - .env

    environment:
      SERVER_PORT: ${USER_SERVICE_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      JAVA_OPTS: ${JAVA_OPTS}
      SPRING_DATASOURCE_URL: ${USER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${POSTGRES_DRIVER}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME}
      SPRING_JPA_OPEN_IN_VIEW: ${SPRING_JPA_OPEN_IN_VIEW}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"

    depends_on:
      postgres:
        condition: service_healthy

      kafka:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${USER_SERVICE_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - fintech-network
